//@version=5
strategy("EMA-VWAP-LongTerm MA SL Strategy", overlay=true,default_qty_type=strategy.percent_of_equity, default_qty_value=100)
visible             = input.bool(true, title="Show Chart lines", group="Strategy Parameters")
stopPercent         = input.float(title="Stop Loss Percent", defval=0.01, step=0.01, group="Strategy Parameters", tooltip="Failsafe Stop Loss Percent Decline", confirm=true)
shortTermDuration   = input.int(title="Short Term Duration", defval=9, confirm=true, group="Strategy Parameters")
shortTermMAType     = input.string(title="Short Term MA", defval="EMA", options=["SMA", "EMA"], confirm=true, group="Strategy Parameters")
longTermDuration    = input.int(title="Long Term Duration", defval=200, confirm=true, group="Strategy Parameters")
longTermMAType      = input.string(title="Long Term MA", defval="SMA", options=["SMA", "EMA"], confirm=true, group="Strategy Parameters")

weeklyShortTerm     = input.int(title="Weekly Short Term Duration", defval=10, confirm=true, group="Strategy Parameters")
weeklyLongTerm      = input.int(title="Weekly Term Duration", defval=30, confirm=true, group="Strategy Parameters")


// STEP 2. See if current bar falls inside the date range
useDateFilter = input.bool(true, title="Filter Date Range of Backtest", group="Backtest Time Period")
backtestStartDate = input.time(timestamp("1 Jan 1995"))
backtestEndDate = input.time(timestamp("1 Jan 2099"))
inTradeWindow = not useDateFilter or (time >= backtestStartDate and time <= backtestEndDate)

// Define the VWAP, EMA 9, and SMA 200 indicators
vwap        = ta.vwap(close)
shortTermMA = shortTermMAType == "EMA" ? ta.ema(close, shortTermDuration): ta.sma(close, shortTermDuration)
longTermMA  = longTermMAType == "SMA" ? ta.sma(close, longTermDuration) : ta.ema(close, longTermDuration) 

// Define the strategy conditions
// entrySignal = inTradeWindow and ta.crossover(ema9, vwap)
// takeProfit = inTradeWindow and ta.crossunder(ema9, vwap) 

// entrySignal = inTradeWindow and ta.crossover(ema9, vwap) and close > sma200
// takeProfit = inTradeWindow and ta.crossunder(ema9, vwap) and close < sma200

var float entryPrice = 0
var float stopPrice = 0
var float risk = 0
var float shortWeeklyMA = na
var float longWeeklyMA = na
//shortPosition   = strategy.position_size < 0
//reward          = longPosition? (close-entryPrice) : (shortPosition? entryPrice-close:na)
noOpenPosition  = strategy.position_size == 0
longPosition    = strategy.position_size > 0
entrySignal     = noOpenPosition and ta.crossover(shortTermMA, vwap) and close > longTermMA
reward          = na(entryPrice) ? na: close - entryPrice
takeProfit      = longPosition and reward > 0 and ta.crossunder(shortTermMA, vwap) and close < longTermMA
actualStopPrcnt = longPosition ? ((-reward) / close) : na
stopLoss        = longPosition and reward < 0 and actualStopPrcnt > stopPercent
rr              = risk > 0 ? reward/risk:na

// Execute trades based on the strategy conditiqons
if (entrySignal) and inTradeWindow
    strategy.entry("Long", strategy.long)

if entrySignal[1]
    entryPrice := open
    risk       := entryPrice*stopPercent
    stopPrice  := entryPrice-risk

if (takeProfit or stopLoss) and inTradeWindow
    // cText     = str.format("Exit {0}, diff:{1, number} entry: {2,number} exit: {3,number}", stopLoss? "SL":"TP",close-entryPrice, entryPrice, close)
    // tpText    = str.format("{0}, RR: {1,number, #.##}",cText, rr)
    // strategy.close(id="Long", comment=stopLoss ? cText : tpText)
    strategy.close(id="Long", comment="Exit " +(stopLoss ? "SL" : "TP"))
    entryPrice := na
    risk       := na
    stopPrice  := na

if timeframe.isweekly
    shortWeeklyMA := ta.sma(close, weeklyShortTerm)
    longWeeklyMA  := ta.sma(close, weeklyLongTerm)

// Plot the indicators on the chart
plot(entryPrice, color=visible? color.lime:na, style=plot.style_linebr)
plot(stopPrice, color=visible?color.red:na, style=plot.style_linebr, offset=-1)
plot(shortTermMA, color=visible?color.yellow:na)
plot(vwap, color=visible?color.white:na, linewidth=2)
plot(longTermMA, color=visible?color.purple:na, linewidth=2)

plot(shortWeeklyMA, color = timeframe.isweekly ? color.blue:na, linewidth=2)
plot(longWeeklyMA,  color = timeframe.isweekly ? color.maroon:na, linewidth=2)